"""Optional conversation summarization: bound token growth in long chats.

Any class in this package that keeps a persistent ``list[dict]`` conversation
-- `~negmas_llm.negotiator.LLMNegotiator`'s ``_conversation_history`` and
PABLO-ve's `~negmas_llm.pablove_components.LLMComponent` in ``"conversation"``
mode -- can opt into collapsing older turns into one LLM-generated summary
once the conversation grows past a threshold, instead of letting it grow
linearly for the life of the negotiation. Disabled by default everywhere it
is offered: it costs an extra LLM call each time it fires, and most
negotiations are short enough that unbounded growth never becomes a problem.

The schedule is driven by the conversation itself, never wall-clock time --
either (or both) of two triggers, checked fresh on every call with no
separate counter to track:

- ``every``: a round count -- once more than this many exchanges (one
  user/assistant pair per call) have accumulated.
- ``over_chars``: a size count -- once the conversation's total character
  length exceeds this many characters (a token-free proxy for prompt size,
  consistent with this package's other length controls, e.g. ``max_words``).

Either trigger firing is enough; :func:`maybe_summarize` re-checks both on
each call, so it fires again once the (now shorter) conversation grows back
past whichever threshold is set.
"""

from __future__ import annotations

from collections.abc import Callable

__all__ = ["DEFAULT_SUMMARY_PROMPT", "maybe_summarize"]

DEFAULT_SUMMARY_PROMPT = """You compress part of an ongoing negotiation \
conversation into a short summary that will REPLACE it going forward.

Preserve every concrete fact: offers made (and their values), utilities \
mentioned, commitments, decisions taken and why, and anything the other \
party said that matters. Drop only redundant phrasing and small talk.

Respond with the summary text only -- no preamble, no JSON."""


def _history_chars(history: list[dict[str, str]]) -> int:
    """Total character length of every message's content in ``history``."""
    return sum(len(m.get("content", "")) for m in history)


def maybe_summarize(
    history: list[dict[str, str]],
    *,
    every: int | None,
    keep: int,
    over_chars: int | None = None,
    raw_call: Callable[[str, str], str],
    system_prompt: str = DEFAULT_SUMMARY_PROMPT,
) -> list[dict[str, str]]:
    """Collapse older exchanges of ``history`` into one summary, if due.

    ``history`` is a flat list of ``{"role": "user"|"assistant", ...}``
    dicts, an even number of entries long (each call appends one user then
    one assistant message) -- the same shape
    `~negmas_llm.negotiator.LLMNegotiator` and PABLO-ve's `LLMComponent` both
    already maintain. An "exchange" is one such pair.

    Due when either trigger fires: more than ``every`` exchanges have
    accumulated, or the conversation's total character length exceeds
    ``over_chars``. Does nothing (returns ``history`` unchanged) when both
    are ``None``/unmet. When due, replaces every exchange except the most
    recent ``keep`` with a single synthetic exchange -- a user turn stating
    the summary, and a placeholder assistant acknowledgement -- generated by
    one call to ``raw_call``. Re-fires next time ``history`` (now ``keep + 1``
    exchanges, shorter) grows back past whichever threshold is set, which
    needs no extra state: the fresh check on each call alone drives the cadence.

    Args:
        history: The conversation to (maybe) collapse.
        every: Exchange-count threshold. ``None`` disables this trigger.
        keep: How many of the most recent exchanges survive verbatim.
        over_chars: Character-count threshold (total content length across
            every message in ``history``). ``None`` disables this trigger.
        raw_call: ``(system, user) -> response_text``, a single one-off
            completion with no history of its own -- e.g. a closure over
            the caller's own model/config resolution. Must not itself touch
            ``history`` (avoiding recursive summarization of the summary call).
        system_prompt: Instructions for the summarization call itself.

    Returns:
        ``history`` unchanged, or a new, shorter list if summarization ran.
    """
    n_exchanges = len(history) // 2
    due_by_count = every is not None and n_exchanges > every
    due_by_size = over_chars is not None and _history_chars(history) > over_chars
    if not (due_by_count or due_by_size):
        return history
    boundary = max(0, n_exchanges - keep) * 2
    to_summarize, kept = history[:boundary], history[boundary:]
    if not to_summarize:
        return history
    transcript = "\n".join(f"{m['role']}: {m['content']}" for m in to_summarize)
    summary_text = raw_call(
        system_prompt,
        f"Summarize this part of the conversation:\n\n{transcript}",
    ).strip()
    if not summary_text:
        return history
    summary_pair = [
        {
            "role": "user",
            "content": (
                "[Summary of earlier turns in this conversation, "
                f"replacing them to save space]\n{summary_text}"
            ),
        },
        {"role": "assistant", "content": "Understood."},
    ]
    return [*summary_pair, *kept]
