"""Optional conversation summarization: bound token growth in long chats.

Any class in this package that keeps a persistent ``list[dict]`` conversation
-- `~negmas_llm.negotiator.LLMNegotiator`'s ``_conversation_history`` and
PABLO-ve's `~negmas_llm.pablove_components.LLMComponent` in ``"conversation"``
mode -- can opt into collapsing older turns into one LLM-generated summary
once the conversation grows past a threshold, instead of letting it grow
linearly for the life of the negotiation. Disabled by default everywhere it
is offered: it costs an extra LLM call each time it fires, and most
negotiations are short enough that unbounded growth never becomes a problem.

The schedule is a round count -- a number of accumulated exchanges (one
user/assistant pair per call) -- not wall-clock time or a byte/token size
threshold: :func:`maybe_summarize` re-checks the same ``every``/``keep``
pair on each call, so it fires again once the conversation has grown back
past the threshold, with no separate counter to track.
"""

from __future__ import annotations

from collections.abc import Callable

__all__ = ["DEFAULT_SUMMARY_PROMPT", "maybe_summarize"]

DEFAULT_SUMMARY_PROMPT = """You compress part of an ongoing negotiation \
conversation into a short summary that will REPLACE it going forward.

Preserve every concrete fact: offers made (and their values), utilities \
mentioned, commitments, decisions taken and why, and anything the other \
party said that matters. Drop only redundant phrasing and small talk.

Respond with the summary text only -- no preamble, no JSON."""


def maybe_summarize(
    history: list[dict[str, str]],
    *,
    every: int | None,
    keep: int,
    raw_call: Callable[[str, str], str],
    system_prompt: str = DEFAULT_SUMMARY_PROMPT,
) -> list[dict[str, str]]:
    """Collapse older exchanges of ``history`` into one summary, if due.

    ``history`` is a flat list of ``{"role": "user"|"assistant", ...}``
    dicts, an even number of entries long (each call appends one user then
    one assistant message) -- the same shape
    `~negmas_llm.negotiator.LLMNegotiator` and PABLO-ve's `LLMComponent` both
    already maintain. An "exchange" is one such pair.

    Does nothing (returns ``history`` unchanged) when ``every`` is ``None``
    or the conversation has not yet grown past it. Otherwise replaces every
    exchange except the most recent ``keep`` with a single synthetic
    exchange -- a user turn stating the summary, and a placeholder assistant
    acknowledgement -- generated by one call to ``raw_call``. Re-fires next
    time ``history`` (now ``keep + 1`` exchanges) grows back past ``every``,
    which needs no extra state: the length check alone drives the cadence.

    Args:
        history: The conversation to (maybe) collapse.
        every: Exchange-count threshold. ``None`` disables summarization.
        keep: How many of the most recent exchanges survive verbatim.
        raw_call: ``(system, user) -> response_text``, a single one-off
            completion with no history of its own -- e.g. a closure over
            the caller's own model/config resolution. Must not itself touch
            ``history`` (avoiding recursive summarization of the summary call).
        system_prompt: Instructions for the summarization call itself.

    Returns:
        ``history`` unchanged, or a new, shorter list if summarization ran.
    """
    if not every:
        return history
    n_exchanges = len(history) // 2
    if n_exchanges <= every:
        return history
    boundary = max(0, n_exchanges - keep) * 2
    to_summarize, kept = history[:boundary], history[boundary:]
    if not to_summarize:
        return history
    transcript = "\n".join(f"{m['role']}: {m['content']}" for m in to_summarize)
    summary_text = raw_call(
        system_prompt,
        f"Summarize this part of the conversation:\n\n{transcript}",
    ).strip()
    if not summary_text:
        return history
    summary_pair = [
        {
            "role": "user",
            "content": (
                "[Summary of earlier turns in this conversation, "
                f"replacing them to save space]\n{summary_text}"
            ),
        },
        {"role": "assistant", "content": "Understood."},
    ]
    return [*summary_pair, *kept]
